# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: migration_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    image: nodejs
    build: .
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db

