# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: migration_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

